# Generated by Django 3.2.9 on 2022-01-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_title', models.CharField(max_length=200, verbose_name='Наименование услуги')),
                ('price_text', models.TextField(verbose_name='Описание услуги')),
            ],
            options={
                'verbose_name': 'Наименование услуги',
                'verbose_name_plural': 'Наименование услуг',
            },
        ),
    ]
