# Generated by Django 3.2.9 on 2022-01-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220119_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='optical',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
