# Generated by Django 3.2.9 on 2022-01-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_optical'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='radius',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10, verbose_name='Радиус кривизны'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='optical',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оптическая сила'),
        ),
    ]
