# Generated by Django 3.2.9 on 2022-02-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220201_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('solutions', 'solutions'), ('glasses', 'glasses'), ('Accessories', 'Accessories'), ('lenses', 'lenses')], db_index=True, default=1, max_length=200, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
