# Generated by Django 3.2.9 on 2022-02-09 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_product_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pubdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('solutions', 'solutions'), ('Accessories', 'Accessories'), ('glasses', 'glasses'), ('lenses', 'lenses')], db_index=True, max_length=200, verbose_name='Категория'),
        ),
    ]
