# Generated by Django 3.2.9 on 2022-02-14 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220209_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('glasses', 'glasses'), ('lenses', 'lenses'), ('solutions', 'solutions')], db_index=True, max_length=200, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='pubdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Годен до:'),
        ),
    ]
