# Generated by Django 3.2.9 on 2022-02-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220214_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['product_id'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('solutions', 'solutions'), ('lenses', 'lenses'), ('Accessories', 'Accessories'), ('glasses', 'glasses')], db_index=True, max_length=200, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='№'),
        ),
    ]
