# Generated by Django 3.2.9 on 2022-06-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220220_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_visit', models.CharField(max_length=200, verbose_name='Наименование')),
                ('Doctor_text', models.TextField(verbose_name='Описание услуги')),
                ('image', models.ImageField(upload_to='gallery', verbose_name='Фото врача')),
                ('image1', models.ImageField(upload_to='gallery', verbose_name='Фото врача')),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('solutions', 'solutions'), ('Accessories', 'Accessories'), ('lenses', 'lenses'), ('glasses', 'glasses')], db_index=True, max_length=200, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='gallery', verbose_name='Вид товара'),
        ),
    ]
