# Generated by Django 3.2.9 on 2022-06-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220616_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Информация о враче', 'verbose_name_plural': 'Информация о врачах'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image1',
            field=models.ImageField(blank=True, upload_to='gallery', verbose_name='Фото врача'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('lenses', 'lenses'), ('Accessories', 'Accessories'), ('solutions', 'solutions'), ('glasses', 'glasses')], db_index=True, max_length=200, verbose_name='Категория'),
        ),
    ]
