# Generated by Django 3.2.9 on 2022-06-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220622_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Doctor_text1',
            field=models.TextField(blank=True, verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Doctor_text',
            field=models.TextField(blank=True, verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery', verbose_name='Фото врача'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('lenses', 'lenses'), ('glasses', 'glasses'), ('solutions', 'solutions')], db_index=True, max_length=200, verbose_name='Категория'),
        ),
    ]
