# Generated by Django 3.2.9 on 2022-06-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20220628_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Doctor_text2',
            field=models.TextField(blank=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Doctor_text3',
            field=models.TextField(blank=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Doctor_text4',
            field=models.TextField(blank=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Doctor_text5',
            field=models.TextField(blank=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Doctor_text6',
            field=models.TextField(blank=True, verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('solutions', 'solutions'), ('Accessories', 'Accessories'), ('glasses', 'glasses'), ('lenses', 'lenses')], db_index=True, max_length=200, verbose_name='Категория'),
        ),
    ]
