# Generated by Django 3.2.9 on 2022-09-04 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_auto_20220628_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('lenses', 'lenses'), ('glasses', 'glasses'), ('solutions', 'solutions')], db_index=True, max_length=200, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Post_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('content', models.TextField(verbose_name='Информация')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пост для комментариев',
                'verbose_name_plural': 'Пост для комментария',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Comments_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, verbose_name='Наименование')),
                ('body', models.TextField(verbose_name='Комментарий')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='comments', to='main.post_user')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_on'],
            },
        ),
    ]
