# Generated by Django 3.2.9 on 2022-09-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20220905_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_slug',
            field=models.SlugField(default=1, max_length=200, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('solutions', 'solutions'), ('lenses', 'lenses'), ('Accessories', 'Accessories'), ('glasses', 'glasses')], db_index=True, max_length=200, verbose_name='Категория'),
        ),
    ]
