# Generated by Django 3.2.9 on 2022-11-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20221004_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('lenses', 'lenses'), ('Accessories', 'Accessories'), ('solutions', 'solutions'), ('glasses', 'glasses')], db_index=True, max_length=200, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
