# Generated by Django 3.2.9 on 2022-11-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('solutions', 'solutions'), ('lenses', 'lenses'), ('glasses', 'glasses'), ('Accessories', 'Accessories')], db_index=True, max_length=200, verbose_name='Категория'),
        ),
    ]
